defaults:
  cards: false
demo:
  cards:
    - title: 'Card title'
      subtitle: 'Byline or date'
      excerpt: 'This is a short card intro'
      url: 'http://google.com'
      img:
        src: 'path/to/image'
        alt: 'Alt text'
    - title: 'Card title'
      subtitle: 'Byline or date'
      excerpt: 'This is a short card intro'
      url: 'http://google.com'
      img:
        src: 'path/to/image'
        alt: 'Alt text'
  class:
    - 't-dark'

schema:
  cards:
    type: array
    description: "All the cards"
    component: 'Card'
  class:
    type: array
    description: "Modifier class for cards. Use for theming maybe?"