defaults:
  tiles: false
demo:
  tiles:
    - title: 'Tile title'
      subtitle: 'Byline or date'
      excerpt: 'This is a short card intro'
      url: 'http://google.com'
      linkText: 'Read more'
      img:
        src: 'path/to/image'
        alt: 'Alt text'
    - title: 'Tile title'
      subtitle: 'Byline or date'
      excerpt: 'This is a short card intro'
      url: 'http://google.com'
      linkText: 'Read more'
      img:
        src: 'path/to/image'
        alt: 'Alt text'
  class:
    - 't-dark'

schema:
  tiles:
    type: array
    description: "All the tiles"
    component: 'Tile'
  class:
    type: array
    description: "Modifier class for tiles. Use for theming"