demo:
  label: 'I am a button!'
  attrs:
    data-foo: 'bar'
  class:
    - test
schema:
  label:
    type: string
    description: "The button's label"
  attrs:
    type: object
    description: "A hash of HTML attributes, e.g:"
    example: >
      {
        "data-tooltip": "my tooltip"
      }
  class:
    type: array
    description: "A list of class names to be added to the button, e.g: ['foo','bar']"
